# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk13

# используем режим обычного пользователя для сборки проекта.
sudo: false

env:
  global:
    - CODECOV_TOKEN="2c90c2f1-a9c1-466f-9361-834214f5ca95"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту michael.dedun@mail.ru если сборка упала
notifications:
  email:
    recipients:
      - michael.dedun@mail.ru
    on_success: never # default: change
    on_failure: always # default: always